"use client";

import { useCallback } from "react";
import { Glyph } from "@/components/ui/Glyph";
import { useToast } from "@/components/ui/Toast";

type Props = {
  eventId: string;
  title: string;
  whenAt: string; // ISO timestamp
  durationMin: number;
  venueName?: string | null;
  label: string;
  toastTitle?: string;
};

function pad2(n: number): string {
  return n.toString().padStart(2, "0");
}

function toIcsDate(date: Date): string {
  // YYYYMMDDTHHMMSSZ in UTC
  return (
    `${date.getUTCFullYear()}${pad2(date.getUTCMonth() + 1)}${pad2(date.getUTCDate())}` +
    `T${pad2(date.getUTCHours())}${pad2(date.getUTCMinutes())}${pad2(date.getUTCSeconds())}Z`
  );
}

function escapeIcs(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/\r\n|\r|\n/g, "\\n")
    .replace(/;/g, "\\;")
    .replace(/,/g, "\\,");
}

/**
 * Client-side .ics generator. Emits a minimal demo-ready calendar payload
 * matching the spec in A9 instructions; not a replacement for the server
 * `/api/events/[eventId]/ics` route — that one folds long lines and is the
 * canonical proof for Judge Mode. This is the in-screen one-click download.
 */
export function IcsExportButton({
  eventId,
  title,
  whenAt,
  durationMin,
  venueName,
  label,
  toastTitle,
}: Props) {
  const toast = useToast();

  const onClick = useCallback(() => {
    const start = new Date(whenAt);
    const end = new Date(start.getTime() + durationMin * 60_000);
    const lines = [
      "BEGIN:VCALENDAR",
      "VERSION:2.0",
      "PRODID:-//showup2move//demo//EN",
      "BEGIN:VEVENT",
      `UID:${escapeIcs(eventId)}@showup2move`,
      `DTSTART:${toIcsDate(start)}`,
      `DTEND:${toIcsDate(end)}`,
      `SUMMARY:${escapeIcs(title)}`,
      `LOCATION:${escapeIcs(venueName ?? "")}`,
      "DESCRIPTION:Generated by ShowUp2Move",
      "END:VEVENT",
      "END:VCALENDAR",
    ];
    const blob = new Blob([`${lines.join("\r\n")}\r\n`], {
      type: "text/calendar;charset=utf-8",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `s2m-${eventId}.ics`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    // Defer revoke so Safari has a moment to start the download.
    setTimeout(() => URL.revokeObjectURL(url), 1000);
    if (toastTitle) {
      toast.push({ title: toastTitle, variant: "success" });
    }
  }, [durationMin, eventId, title, toast, toastTitle, venueName, whenAt]);

  return (
    <button
      type="button"
      onClick={onClick}
      className="btn-s2m btn-secondary"
      style={{
        width: "100%",
        padding: "10px 16px",
        minHeight: 44,
        fontSize: 14,
        gap: 8,
      }}
    >
      <Glyph.cal size={18} />
      {label}
    </button>
  );
}
